version: '3.7'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"

  web:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
     
