# Generated by Django 5.0.3 on 2024-05-16 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='check_in',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reminder',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
