# Generated by Django 5.0.3 on 2024-07-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_customuser_check_in_customuser_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_check_in_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_reminder_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
