name: Deploy to GitHub Pages from frontend folder

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'latest'  # Use the latest version of Node.js

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build the project
        run: |
          cd frontend
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist  # Path to your build output directory
